require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - '**/config.ru'
    - '**/Rakefile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
Documentation:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/GlobalStdStream:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: true
Style/SingleArgumentDig:
  Enabled: true
Style/SlicingWithRange:
  Enabled: false
Style/StringConcatenation:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/NonDeterministicRequireOrder:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/DuplicateElsifCondition:
  Enabled: false
Lint/DuplicateRescueException:
  Enabled: false
Lint/EmptyConditionalBody:
  Enabled: false
Lint/FloatComparison:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: false
Lint/OutOfRangeRegexpRef:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/SelfAssignment:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Lint/TopLevelReturnWithArgument:
  Enabled: false
Lint/UnreachableLoop:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'app/admin/*'
    - 'spec/**/*_spec.rb'
    - 'spec/factories/*'
    - 'config/routes.rb'
  Max: 33
Metrics/AbcSize:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 15
Layout/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 25
Metrics/PerceivedComplexity:
  Max: 12
Naming/MemoizedInstanceVariableName:
  Enabled: false
RSpec/ExampleLength:
  Max: 50
RSpec/MultipleExpectations:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'
    - 'spec/scenarios/**/*'
Style/DateTime:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%w': ()
Style/RaiseArgs:
  EnforcedStyle: compact
Style/RegexpLiteral:
  StyleGuide: slashes
Style/GuardClause:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/StringLiterals:
  EnforcedStyle: single_quotes
