DATABASE: 'gss'
DATABASE_HOST: 'localhost'
DATABASE_PASSWORD: 'szikaka'
DATABASE_POOL: 5
DATABASE_PORT: ''
DATABASE_USERNAME: 'staszek'

SECRET_KEY_BASE: ''

DEVELOPMENT_DATABASE: 'gss-dev'
TEST_DATABASE: 'gss-test'
